### ISSUE TITLE
getting the following error

### ISSUE THREAD

**Issue by adulion** [machuga/codeigniter-filter#1]
getting the following error-

A PHP Error was encountered

Severity: Notice

Message: Undefined offset: 0

Filename: core/MY_Controller.php

Line Number: 44

using the download and 

protected $before_filter = array(
        'action' => 'redirect_if_not_logged_in',
        'except' => array('index')
    );
in my events controller- what am i missing?

**Comment by machuga** [comment]
What is on line 44?  That is a blank line in the source code for me.

**Comment by adulion** [comment]
line 44 is

$this->filter($method, $args[0]);

args is an empty array

**Comment by machuga** [comment]
Okay, try using the latest release.  I put in some extra handling so it should be okay now (albeit not pretty at the moment)

**Comment by adulion** [comment]
thanks for sorting this issue- you may wish to create an example controller and move the example callbacks to it, i think it may keep the my_controller cleaner

**Comment by machuga** [comment]
I should definitely document it better.  I'll likely add an example to to the README to make it a bit more obvious what's going on.  If you need any additional examples I do have a blog post about it at http://matthewmachuga.com/post/7181182435/codeigniter-filter-revisited.
